[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[cursor]
style = "Beam"

[window]
padding = { x = 12, y = 10  }
dynamic_padding = true
decorations = "full"          
startup_mode = "Windowed"    
title = "Alacritty"
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[colors.primary]
background = "#24273a"  
foreground = "#cad3f5"  
dim_foreground = "#a5adcb"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#24273a"        
cursor = "#f4dbd6"       

[colors.normal]
black = "#494d64"      
red = "#ed8796"         
green = "#a6da95"       
yellow = "#eed49f"      
blue = "#8aadf4"        
magenta = "#c6a0f6"     
cyan = "#8bd5ca"        
white = "#b8c0e0"       

[colors.bright]
black = "#5b6078"       
red = "#ed8796"
green = "#a6da95"
yellow = "#f5a97f"       
blue = "#8aadf4"
magenta = "#f5bde6"     
cyan = "#91d7e3"        
white = "#f4dbd6"       

[colors.dim]
black = "#363a4f"       
red = "#ee99a0"         
green = "#6e738d"       
yellow = "#939ab7"      
blue = "#7dc4e4"        
magenta = "#b7bdf8"     
cyan = "#7dc4e4"        
white = "#a5adcb"       

[colors.search]
matches = { foreground = "#24273a", background = "#a5adcb" }
focused_match = { foreground = "#24273a", background = "#cad3f5" }

[colors.hints]
start = { foreground = "#24273a", background = "#a5adcb" }
end = { foreground = "#24273a", background = "#5b6078" }


